name: app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation:
  gap:
  go_router: 15.0.0
  go_router_builder:
  hooks_riverpod:
  intl:
  json_annotation: ^4.9.0
  riverpod_annotation:

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  pedantic_mono: any
  riverpod_generator:

flutter:

  uses-material-design: true
